seed: 0
output_dir: './output'  # 当前不支持自定义修改，请勿修改该默认值
load_checkpoint: '' # /home/xiaohuawen/RLHF/mindrlhf/ward_model_train_tutorial/output_12.20/checkpoint
auto_trans_ckpt: False  # If true, auto transform load_checkpoint to load in distributed model
src_strategy_path_or_dir: ''
only_save_strategy: False
resume_training: False
use_parallel: True
run_mode: 'train'
checkpoint_name_or_path: '/data1/test'

trainer:
  type: CausalLanguageModelingTrainer
  model_name: 'baichuan2_13b'
# if True, do evaluate during the training process. if false, do nothing.
# note that the task trainer should support _evaluate_in_training function.
do_eval: False

runner_config:
  epochs: 1
  batch_size: 2
  sink_mode: True
  sink_size: 2

optimizer:
  type: FP32StateAdamWeightDecay
  beta1: 0.9
  beta2: 0.95
  eps: 1.e-8
  learning_rate: 2.e-5
  weight_decay: 0.0

# dataset
train_dataset: &train_dataset
  data_loader:
    type: MindDataset
    dataset_dir: "/data2/jiaoy/dataset/baichuan/baichuan_16m.mindrecord"
    shuffle: True
  input_columns: ["chosen_input_ids", "chosen_attention_mask",
                  "rejected_input_ids", "rejected_attention_mask",
                  "position_id", "loss_mask", "end_ind"]
  output_columns: ["input_ids", "position_id", "attention_mask", "loss_mask", "end_ind"]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 2 
  repeat: 1
  numa_enable: False
  prefetch_size: 1
  pad_token_id: 0
train_dataset_task:
  type: RewardModelDataset
  dataset_config: *train_dataset
# if True, do evaluate during the training process. if false, do nothing.
# note that the task trainer should support _evaluate_in_training function.
do_eval: False
eval_step_interval: -1        # num of step intervals between each eval, -1 means no step end eval.
eval_epoch_interval: 50        # num of epoch intervals between each eval, 1 means eval on every epoch end.

eval_dataset: &eval_dataset
  data_loader:
    type: MindDataset
    dataset_dir: "/data2/jiaoy/dataset/baichuan/baichuan_16m.mindrecord"
    shuffle: False
  input_columns: ["chosen_input_ids", "chosen_attention_mask",
                  "rejected_input_ids", "rejected_attention_mask",
                  "position_id", "loss_mask", "end_ind"]
  output_columns: ["input_ids", "position_id", "attention_mask", "loss_mask", "end_ind"]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: False
  batch_size: 2 
  repeat: 1
  numa_enable: False
  prefetch_size: 1
  pad_token_id: 0
eval_dataset_task:
  type: RewardModelDataset
  dataset_config: *eval_dataset

parallel:
  parallel_mode: 1 # 0-dataset, 1-semi, 2-auto, 3-hybrid
  gradients_mean: False
  enable_alltoall: False
  full_batch: True
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: True
  strategy_ckpt_save_file: "./ckpt_strategy.ckpt"
  parallel_optimizer_config:
    gradient_accumulation_shard: False
    parallel_optimizer_threshold: 64
# default parallel of device num = 8 910A
parallel_config:
  data_parallel: 1
  model_parallel: 8
  pipeline_stage: 1
  optimizer_shard: True
  micro_batch_num: 1
  vocab_emb_dp: False
  gradient_aggregation_group: 4
# when model parallel is greater than 1, we can set micro_batch_interleave_num=2, that may accelerate the train process.
micro_batch_interleave_num: 1

recompute_config:
  recompute: True
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: True

callbacks:
  - type: MFLossMonitor
  - type: CheckpointMointor
    prefix: "baichuan2_13b"
    save_checkpoint_steps: 1000
    keep_checkpoint_max: 5
    integrated_save: False
    async_save: False
  - type: ObsMonitor

# mindspore context init config
context:
  mode: 0 # 0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  enable_graph_kernel: False
  graph_kernel_flags: "--disable_expand_ops=Softmax,Dropout --enable_parallel_fusion=true --reduce_fuse_depth=8 --enable_auto_tensor_inplace=true"
  max_call_depth: 10000
  max_device_memory: "59GB"
  save_graphs: False
  save_graphs_path: "./graph"
  device_id: 0


model:
  model_config:
    type: LlamaConfig
    batch_size: 2 # add for increase predict
    seq_length: 4096
    checkpoint_path: '/data2/jiaoy/RLHF/Baichuan2-13B-Chat.ckpt'
    #checkpoint_path: '/data2/Baichuan2/mindformers-dev2/output_baichuan_0110_2/checkpoint/rank_0/baichuan2_13b_rank_0-500_2.ckpt'
    hidden_size: 5120
    num_layers: 40
    num_heads: 40
    vocab_size: 125696
    multiple_of: 128
    rms_norm_eps: 1.0e-6
    bos_token_id: 1
    eos_token_id: 2
    pad_token_id: 0
    ignore_token_id: -100
    compute_dtype: "float16"
    layernorm_compute_type: "float32"
    softmax_compute_type: "float32"
    param_init_type: "float16"
    use_past: False
    pretrain_seqlen: 2048 # seqlen of the pretrain checkpoint: 2048 for llama and 4096 for llama2
    extend_method: "None" # support "None", "PI", "NTK"
    compute_in_2d: True
    use_flash_attention: False
    offset: 0
    use_past_shard: False
    checkpoint_name_or_path: ''
    repetition_penalty: 1
    max_decode_length: 2048
    top_k: 3
    top_p: 1
    do_sample: False
  arch:
    type: Baichuan13BV2Reward

processor:
  return_tensors: ms
  tokenizer:
    vocab_file: "/data2/dataset/baichuan/tokenizer.model"
    unk_token: '<unk>'
    bos_token: '<s>'
    eos_token: '</s>'
    pad_token: '<unk>'
    type: Baichuan2Tokenizer
  type: LlamaProcessor

metric:
  type: PerplexityMetric

runner_wrapper:
  type: MFTrainOneStepCell
  scale_sense:
    type: DynamicLossScaleUpdateCell
    loss_scale_value: 128
    scale_factor: 2
    scale_window: 100
  use_clip_grad: True

eval_callbacks:
  - type: ObsMonitor

auto_tune: False
filepath_prefix: './autotune'
autotune_per_step: 10

profile: False
profile_start_step: 1
profile_stop_step: 10
init_start_profile: False
profile_communication: False
profile_memory: True
layer_scale: False
layer_decay: 0.65
lr_scale_factor: 256

remote_save_url: "Please input obs url on AICC platform."
